// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr9jg17sanRq2b-nIqLiM9z-7dLwAn3UY',
    appId: '1:208253993337:web:37f8e5501003dcdb46afa8',
    messagingSenderId: '208253993337',
    projectId: 'navigater-d4f2e',
    authDomain: 'navigater-d4f2e.firebaseapp.com',
    storageBucket: 'navigater-d4f2e.appspot.com',
    measurementId: 'G-8JH0CPX89M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6ul-21HZib3amy51Rja97wjpSbboYLjw',
    appId: '1:208253993337:android:38a1a5ebc2c5a10246afa8',
    messagingSenderId: '208253993337',
    projectId: 'navigater-d4f2e',
    storageBucket: 'navigater-d4f2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2O2UmAQ1uWaO48COlcYmmw3PraEl9lJg',
    appId: '1:208253993337:ios:220f3a3cbcc1cb0c46afa8',
    messagingSenderId: '208253993337',
    projectId: 'navigater-d4f2e',
    storageBucket: 'navigater-d4f2e.appspot.com',
    iosBundleId: 'com.example.brewRounds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2O2UmAQ1uWaO48COlcYmmw3PraEl9lJg',
    appId: '1:208253993337:ios:4f61c4eeab1cd5ca46afa8',
    messagingSenderId: '208253993337',
    projectId: 'navigater-d4f2e',
    storageBucket: 'navigater-d4f2e.appspot.com',
    iosBundleId: 'com.example.brewRounds.RunnerTests',
  );
}
